import { icon } from "../components/icons.js";
import { escapeHtml, formatDate } from "../utils/format.js";

export function renderClientsView({ clients, currentUser, toolbar = "", pager = "" }) {
    if (!clients.length) return `<section class="panel">${toolbar}<div class="empty">Aucun client.</div>${pager}</section>`;
    return `<section class="panel">${toolbar}<div class="table-wrap"><table><thead><tr><th>Nom</th><th>Email</th><th>Téléphone</th><th>Adresse</th><th></th></tr></thead><tbody>${clients.map((client) => `<tr><td data-label="Nom"><strong>${escapeHtml(client.nom)}</strong></td><td data-label="Email">${escapeHtml(client.email || "—")}</td><td data-label="Téléphone">${escapeHtml(client.telephone || "—")}</td><td data-label="Adresse">${escapeHtml(client.adresse || "—")}</td><td data-label="Actions" class="actions"><button class="secondary" data-open-client="${client.id}">Ouvrir</button>${currentUser.role === "ADMIN" ? `<button class="danger" data-delete-client="${client.id}">Supprimer</button>` : ""}</td></tr>`).join("")}</tbody></table></div>${pager}</section>`;
}

export function renderEquipmentsView({ equipments, currentUser, toolbar = "", pager = "" }) {
    if (!equipments.length) return `<section class="panel">${toolbar}<div class="empty">Aucun matériel.</div>${pager}</section>`;
    return `<section class="panel">${toolbar}<div class="table-wrap"><table><thead><tr><th>Client</th><th>Type</th><th>Marque / modèle</th><th>N° série</th><th></th></tr></thead><tbody>${equipments.map((equipment) => `<tr><td data-label="Client">${escapeHtml(equipment.client_nom)}</td><td data-label="Type">${escapeHtml(equipment.type || "—")}</td><td data-label="Marque / modèle">${escapeHtml([equipment.marque, equipment.modele].filter(Boolean).join(" · ") || "—")}</td><td data-label="N° série">${escapeHtml(equipment.numero_serie || "—")}</td><td data-label="Actions" class="actions">${currentUser.role === "ADMIN" ? `<button class="secondary" data-edit-equipment="${equipment.id}">${icon("edit")} Modifier</button><button class="danger" data-delete-equipment="${equipment.id}">Supprimer</button>` : ""}</td></tr>`).join("")}</tbody></table></div>${pager}</section>`;
}

export function renderTeamView({ technicians }) {
    if (!technicians.length) return `<section class="panel"><div class="empty">Aucun technicien. Utilisez “Ajouter” pour créer le premier compte.</div></section>`;
    return `<section class="panel"><div class="panel-head"><div><h2>Collaborateurs techniques</h2><p class="muted">La désactivation conserve le compte. La suppression définitive efface le technicien de la base et désassigne ses interventions.</p></div></div><div class="table-wrap"><table><thead><tr><th>Nom</th><th>Email</th><th>Statut</th><th>Créé le</th><th>Actions</th></tr></thead><tbody>${technicians.map((user) => `<tr><td data-label="Nom"><strong>${escapeHtml(user.nom)}</strong></td><td data-label="Email">${escapeHtml(user.email)}</td><td data-label="Statut"><span class="badge ${user.actif ? "" : "off"}">${user.actif ? "Actif" : "Désactivé"}</span></td><td data-label="Créé le">${formatDate(user.created_at)}</td><td data-label="Actions" class="actions"><button class="secondary" data-edit-technician-email="${user.id}">Modifier l’e-mail</button>${user.actif ? `<button class="secondary" data-disable-technician="${user.id}">Désactiver</button>` : `<button class="primary" data-enable-technician="${user.id}">Réactiver</button>`}<button class="danger" data-delete-technician="${user.id}" data-technician-name="${escapeHtml(user.nom)}">Supprimer définitivement</button></td></tr>`).join("")}</tbody></table></div></section>`;
}
